from app.models.activity import ActivityFeed, RecentEdge
from app.models.common import Paginated
from app.models.config import ConfigEntry, ConfigUpdate
from app.models.discover import (
    BridgeCandidate,
    BridgeClassification,
    ClassifyBridgeRequest,
    TriangleCandidate,
)
from app.models.edge import (
    RESOLVABLE_EDGE_TYPES,
    EdgeCreate,
    EdgeDetail,
    EdgeResolveRequest,
    EdgeSummary,
    EdgeType,
    NeighborResult,
)
from app.models.embedding_job import (
    AdminStatus,
    EmbeddingJob,
    EmbeddingJobCounts,
    EmbeddingJobList,
    EmbeddingJobStatus,
    RetryAllResponse,
)
from app.models.graph import GraphData, GraphEdgeRef, GraphNodeRef
from app.models.ingest import (
    ChunkResult,
    IngestDocumentRequest,
    IngestDocumentResponse,
    IngestSourceCreate,
    LiteratureCandidate,
    PendingIngestResponse,
)
from app.models.node import (
    FleetingCreate,
    LiteratureCreate,
    NodeDetail,
    NodeRef,
    NodeSummary,
    NodeType,
    NodeUpdate,
    PermanentCreate,
    StructureCreate,
)
from app.models.project import (
    Draft,
    DraftUpdate,
    ProjectCreate,
    ProjectDetail,
    ProjectMode,
    ProjectScope,
    ProjectScopeUpdate,
    ProjectSummary,
    SessionMode,
    SessionStatus,
    WorkSession,
    WorkSessionCreate,
    WorkSessionUpdate,
)
from app.models.timeline import (
    ActSpan,
    ActSpanCreate,
    ProseStatus,
    SceneContextItem,
    SceneContextResponse,
    StoryEventCreate,
    TimelineEvent,
    TimelineLane,
    TimelinePositionUpdate,
    TimelineResponse,
)
from app.models.rag import (
    ClusterLinkProposal,
    ClusterSuggestRequest,
    ClusterSuggestResponse,
    EdgeTraversed,
    LinkSuggestion,
    NodeUsed,
    PermanentCandidate,
    RagRequest,
    RagResponse,
    SaveAnswerRequest,
    ScopedRagRequest,
    SuggestLinksResponse,
    SuggestPermanentResponse,
)
from app.models.search import (
    DedupRequest,
    DedupResponse,
    DedupResult,
    SearchRequest,
    SearchResponse,
    SearchResult,
)
from app.models.source import (
    SourceCreate,
    SourceDetail,
    SourceRef,
    SourceSummary,
    SourceType,
    SourceUpdate,
)
from app.models.stats import CorpusStats
from app.models.tag import TagCreate, TagRef, TagUpdate

# EdgeSummary is imported under TYPE_CHECKING in node.py to break the mutual
# dependency at runtime. Now that both modules are loaded, resolve it.
NodeDetail.model_rebuild()

# ProjectDetail embeds NodeDetail and forward-references WorkSession; rebuild
# now that NodeDetail's own forward references are resolved.
ProjectDetail.model_rebuild()

__all__ = [
    "ActivityFeed",
    "RecentEdge",
    "Paginated",
    "ConfigEntry",
    "ConfigUpdate",
    "TagCreate",
    "TagRef",
    "TagUpdate",
    "FleetingCreate",
    "LiteratureCreate",
    "NodeDetail",
    "NodeRef",
    "NodeSummary",
    "NodeType",
    "NodeUpdate",
    "PermanentCreate",
    "StructureCreate",
    "Draft",
    "DraftUpdate",
    "ProjectCreate",
    "ProjectDetail",
    "ProjectMode",
    "ProjectScope",
    "ProjectScopeUpdate",
    "ProjectSummary",
    "SessionMode",
    "SessionStatus",
    "WorkSession",
    "WorkSessionCreate",
    "WorkSessionUpdate",
    "ActSpan",
    "ActSpanCreate",
    "ProseStatus",
    "SceneContextItem",
    "SceneContextResponse",
    "StoryEventCreate",
    "TimelineEvent",
    "TimelineLane",
    "TimelinePositionUpdate",
    "TimelineResponse",
    "EdgeCreate",
    "EdgeDetail",
    "EdgeResolveRequest",
    "EdgeSummary",
    "EdgeType",
    "NeighborResult",
    "RESOLVABLE_EDGE_TYPES",
    "SourceCreate",
    "SourceDetail",
    "SourceRef",
    "SourceSummary",
    "SourceType",
    "SourceUpdate",
    "PermanentCandidate",
    "SuggestPermanentResponse",
    "LinkSuggestion",
    "SuggestLinksResponse",
    "ClusterSuggestRequest",
    "ClusterLinkProposal",
    "ClusterSuggestResponse",
    "RagRequest",
    "RagResponse",
    "ScopedRagRequest",
    "SaveAnswerRequest",
    "NodeUsed",
    "EdgeTraversed",
    "SearchRequest",
    "SearchResponse",
    "SearchResult",
    "DedupRequest",
    "DedupResponse",
    "DedupResult",
    "GraphData",
    "GraphEdgeRef",
    "GraphNodeRef",
    "ChunkResult",
    "IngestDocumentRequest",
    "IngestDocumentResponse",
    "IngestSourceCreate",
    "LiteratureCandidate",
    "PendingIngestResponse",
    "BridgeCandidate",
    "BridgeClassification",
    "ClassifyBridgeRequest",
    "TriangleCandidate",
    "CorpusStats",
    "AdminStatus",
    "EmbeddingJob",
    "EmbeddingJobCounts",
    "EmbeddingJobList",
    "EmbeddingJobStatus",
    "RetryAllResponse",
]
