import type { components } from "./api-types";

export type NodeDetail = components["schemas"]["NodeDetail"];
export type NodeSummary = components["schemas"]["NodeSummary"];
export type NodeRef = components["schemas"]["NodeRef"];
export type SuggestPermanentResponse =
  components["schemas"]["SuggestPermanentResponse"];
export type PermanentCandidate = components["schemas"]["PermanentCandidate"];
export type SuggestLinksResponse =
  components["schemas"]["SuggestLinksResponse"];
export type LinkSuggestion = components["schemas"]["LinkSuggestion"];
export type PaginatedNodes = components["schemas"]["Paginated_NodeSummary_"];
export type TagRef = components["schemas"]["TagRef"];
export type EdgeDetail = components["schemas"]["EdgeDetail"];
export type EdgeType = components["schemas"]["EdgeCreate"]["type"];
export type EdgeResolveRequest = components["schemas"]["EdgeResolveRequest"];
export type SourceSummary = components["schemas"]["SourceSummary"];
export type SourceDetail = components["schemas"]["SourceDetail"];
export type SourceCreate = components["schemas"]["SourceCreate"];
// SourceUpdate is generated by openapi-typescript once the backend exposes it.
// Until `pnpm types` runs it may be absent — fall back to a structural type.
export type SourceUpdate = Partial<Omit<SourceCreate, "id">>;
export type SearchResponse = components["schemas"]["SearchResponse"];
export type SearchResult = components["schemas"]["SearchResult"];
export type DedupResponse = components["schemas"]["DedupResponse"];
export type DedupResult = components["schemas"]["DedupResult"];
export type RagResponse = components["schemas"]["RagResponse"];
export type RagMode = NonNullable<components["schemas"]["RagRequest"]["mode"]>;
export type ActivityFeed = components["schemas"]["ActivityFeed"];
export type RecentEdge = components["schemas"]["RecentEdge"];
// Phase 9 (ADR-063)
export type ProjectSummary = components["schemas"]["ProjectSummary"];
export type ProjectDetail = components["schemas"]["ProjectDetail"];
export type ProjectScope = components["schemas"]["ProjectScope"];
export type ProjectScopeUpdate = components["schemas"]["ProjectScopeUpdate"];
export type ProjectCreate = components["schemas"]["ProjectCreate"];
export type ProjectResolveResponse =
  components["schemas"]["ProjectResolveResponse"];
export type Draft = components["schemas"]["Draft"];
export type WorkSession = components["schemas"]["WorkSession"];
export type WorkSessionCreate = components["schemas"]["WorkSessionCreate"];
export type WorkSessionUpdate = components["schemas"]["WorkSessionUpdate"];
// Literal aliases are inlined by openapi-typescript, so we extract them from
// the parent models rather than naming them directly.
export type ProjectMode = ProjectScope["mode"];
export type SessionMode = WorkSession["mode"];
export type SessionStatus = WorkSession["status"];
export type ClusterSuggestResponse =
  components["schemas"]["ClusterSuggestResponse"];
export type ClusterLinkProposal = components["schemas"]["ClusterLinkProposal"];
export type TriangleCandidate = components["schemas"]["TriangleCandidate"];
export type NodeUsed = components["schemas"]["NodeUsed"];
export type EdgeTraversed = components["schemas"]["EdgeTraversed"];
export type GraphData = components["schemas"]["GraphData"];
export type GraphNodeRef = components["schemas"]["GraphNodeRef"];
export type GraphEdgeRef = components["schemas"]["GraphEdgeRef"];
export type IngestDocumentResponse =
  components["schemas"]["IngestDocumentResponse"];
export type IngestSourceCreate = components["schemas"]["IngestSourceCreate"];
export type ChunkResult = components["schemas"]["ChunkResult"];
export type LiteratureCandidate = components["schemas"]["LiteratureCandidate"];
export type PendingIngestResponse =
  components["schemas"]["PendingIngestResponse"];
export type EmbeddingJob = components["schemas"]["EmbeddingJob"];
export type EmbeddingJobCounts = components["schemas"]["EmbeddingJobCounts"];
export type EmbeddingJobList = components["schemas"]["EmbeddingJobList"];
export type EmbeddingJobStatus = EmbeddingJob["status"];
export type AdminStatus = components["schemas"]["AdminStatus"];
// CorpusStats lands in api-types after `pnpm types`. Structural fallback for now.
export type CorpusStats = {
  nodes_by_type: Record<string, number>;
  edges: number;
  sources: number;
  tags: number;
  inbox: number;
  last_processed_at: string | null;
};
// BridgeCandidate is not yet in the generated schema — define manually from backend model
export type BridgeCandidate = {
  node_a: NodeRef;
  node_b: NodeRef;
  similarity: number;
};
export type BridgeClassification =
  components["schemas"]["BridgeClassification"];

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { "Content-Type": "application/json" },
    cache: "no-store",
    ...options,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`${res.status}: ${text}`);
  }
  if (res.status === 204) return undefined as T;
  return res.json() as Promise<T>;
}

export function createFleetingNode(
  title: string,
  content: string,
): Promise<NodeDetail> {
  return request("/api/v1/nodes/fleeting", {
    method: "POST",
    body: JSON.stringify({ title, content }),
  });
}

export function getInboxNodes(): Promise<NodeSummary[]> {
  return request("/api/v1/nodes/inbox");
}

export function getNode(id: string): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${id}`);
}

export function updateNode(
  id: string,
  patch: {
    title?: string;
    content?: string;
    summary?: string;
    source_id?: string | null;
    tag_ids?: string[] | null;
    // Slice 5 (ADR-064/071): event-specific PATCH support. Explicit null
    // clears the column; omitting the field leaves it unchanged.
    story_time?: string | null;
    prose_status?: string | null;
    manuscript_location?: string | null;
  },
): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${id}`, {
    method: "PATCH",
    body: JSON.stringify(patch),
  });
}

export function markNodeProcessed(id: string): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${id}/process`, { method: "POST" });
}

export function deleteNode(id: string): Promise<void> {
  return request(`/api/v1/nodes/${id}`, { method: "DELETE" });
}

export function suggestPermanent(
  id: string,
): Promise<SuggestPermanentResponse> {
  return request(`/api/v1/rag/suggest-permanent/${id}`, { method: "POST" });
}

export function createPermanentNode(data: {
  title: string;
  content: string;
  summary?: string;
  tag_ids?: string[];
}): Promise<NodeDetail> {
  return request("/api/v1/nodes/permanent", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export interface ListNodesFilters {
  noSummary?: boolean;
  noOutgoing?: boolean;
  noEdges?: boolean;
  summaryMaxLength?: number;
}

export function listNodes(
  type?: string,
  page = 1,
  pageSize = 50,
  filters: ListNodesFilters = {},
): Promise<PaginatedNodes> {
  const params = new URLSearchParams({
    page: String(page),
    page_size: String(pageSize),
  });
  if (type) params.set("type", type);
  if (filters.noSummary) params.set("no_summary", "true");
  if (filters.noOutgoing) params.set("no_outgoing", "true");
  if (filters.noEdges) params.set("no_edges", "true");
  if (filters.summaryMaxLength !== undefined) {
    params.set("summary_max_length", String(filters.summaryMaxLength));
  }
  return request(`/api/v1/nodes?${params}`);
}

export function createLiteratureNode(data: {
  title: string;
  content: string;
  summary?: string;
  source_id: string;
  tag_ids?: string[];
}): Promise<NodeDetail> {
  return request("/api/v1/nodes/literature", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function createStructureNode(data: {
  title: string;
  content: string;
  summary?: string;
}): Promise<NodeDetail> {
  return request("/api/v1/nodes/structure", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function searchNodes(q: string, limit = 10): Promise<NodeRef[]> {
  const params = new URLSearchParams({ q, limit: String(limit) });
  return request(`/api/v1/nodes/search?${params}`);
}

// Tags
export function listTags(): Promise<TagRef[]> {
  return request("/api/v1/tags");
}

export function createTag(name: string, color?: string): Promise<TagRef> {
  return request("/api/v1/tags", {
    method: "POST",
    body: JSON.stringify({ name, color }),
  });
}

// Edges
export function createEdge(data: {
  from_id: string;
  to_id: string;
  type: EdgeType;
  note?: string;
  classifier_rationale?: string;
}): Promise<EdgeDetail> {
  return request("/api/v1/edges", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function deleteEdge(edgeId: string): Promise<void> {
  return request(`/api/v1/edges/${edgeId}`, { method: "DELETE" });
}

// ADR-082: the edge-note authoring loop. Edit why a relationship exists / what
// it means; `note: null` clears it.
export function updateEdge(
  edgeId: string,
  data: { note: string | null },
): Promise<EdgeDetail> {
  return request(`/api/v1/edges/${edgeId}`, {
    method: "PATCH",
    body: JSON.stringify(data),
  });
}

// ADR-059: resolve a tension edge (CONTRADICTS / QUESTIONS only). The optional
// `resolved_by_node_id` points to a synthesis note that supersedes the
// tension. POST is idempotent; DELETE clears the resolved state.
export function resolveEdge(
  edgeId: string,
  data: EdgeResolveRequest = {},
): Promise<EdgeDetail> {
  return request(`/api/v1/edges/${edgeId}/resolve`, {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function unresolveEdge(edgeId: string): Promise<EdgeDetail> {
  return request(`/api/v1/edges/${edgeId}/resolve`, { method: "DELETE" });
}

// RAG
export function suggestLinks(nodeId: string): Promise<SuggestLinksResponse> {
  return request(`/api/v1/rag/suggest-links/${nodeId}`, { method: "POST" });
}

// Sources
export function listSources(): Promise<SourceSummary[]> {
  return request("/api/v1/sources");
}

export function getSource(id: string): Promise<SourceDetail> {
  return request(`/api/v1/sources/${id}`);
}

// `status` defaults to "user_supplied" server-side; callers only need to pass
// it when they explicitly want a different status (e.g. learning-map flow
// marks suggestions with status="suggested").
export function createSource(
  data: Omit<SourceCreate, "id" | "status"> & {
    status?: SourceCreate["status"];
  },
): Promise<SourceDetail> {
  return request("/api/v1/sources", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function updateSource(
  id: string,
  data: SourceUpdate,
): Promise<SourceDetail> {
  return request(`/api/v1/sources/${id}`, {
    method: "PATCH",
    body: JSON.stringify(data),
  });
}

export function deleteSource(id: string): Promise<void> {
  return request(`/api/v1/sources/${id}`, { method: "DELETE" });
}

export function openSource(
  id: string,
): Promise<{ opened: string; warning?: string }> {
  return request(`/api/v1/sources/${id}/open`);
}

// Search
export function searchSemantic(
  query: string,
  limit = 20,
): Promise<SearchResponse> {
  return request("/api/v1/search/semantic", {
    method: "POST",
    body: JSON.stringify({ query, limit }),
  });
}

export function searchFulltext(
  query: string,
  limit = 20,
): Promise<SearchResponse> {
  return request("/api/v1/search/fulltext", {
    method: "POST",
    body: JSON.stringify({ query, limit }),
  });
}

export function searchHybrid(
  query: string,
  limit = 20,
): Promise<SearchResponse> {
  return request("/api/v1/search/hybrid", {
    method: "POST",
    body: JSON.stringify({ query, limit }),
  });
}

// ADR-062: capture-time dedup search. Returns raw clamped-cosine similarities
// (absolute, not rank-normalized) so callers can threshold against a fixed
// "looks like a duplicate" bar.
export function searchDedup(query: string, limit = 8): Promise<DedupResponse> {
  return request("/api/v1/search/dedup", {
    method: "POST",
    body: JSON.stringify({ query, limit }),
  });
}

// Graph
export function getGraphData(includeFlecting = true): Promise<GraphData> {
  return request(`/api/v1/graph/data?include_fleeting=${includeFlecting}`);
}

// Ingest
export function ingestDocument(body: {
  content: string;
  source_id?: string;
  source?: IngestSourceCreate;
}): Promise<IngestDocumentResponse> {
  return request("/api/v1/ingest/document", {
    method: "POST",
    body: JSON.stringify(body),
  });
}

export function getPendingIngest(
  sourceId: string,
): Promise<PendingIngestResponse> {
  return request(`/api/v1/ingest/pending/${sourceId}`);
}

export function clearPendingIngest(sourceId: string): Promise<void> {
  return request(`/api/v1/ingest/pending/${sourceId}`, { method: "DELETE" });
}

// Discover
export function listOrphans(
  opts: {
    limit?: number;
    offset?: number;
    nodeType?: string;
  } = {},
): Promise<NodeSummary[]> {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.offset !== undefined) params.set("offset", String(opts.offset));
  if (opts.nodeType) params.set("node_type", opts.nodeType);
  const qs = params.toString();
  return request(`/api/v1/discover/orphans${qs ? `?${qs}` : ""}`);
}

export function listStale(
  opts: {
    limit?: number;
    offset?: number;
    nodeType?: string;
    excludeFleeting?: boolean;
  } = {},
): Promise<NodeSummary[]> {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.offset !== undefined) params.set("offset", String(opts.offset));
  if (opts.nodeType) params.set("node_type", opts.nodeType);
  if (opts.excludeFleeting !== undefined)
    params.set("exclude_fleeting", String(opts.excludeFleeting));
  const qs = params.toString();
  return request(`/api/v1/discover/stale${qs ? `?${qs}` : ""}`);
}

export function listBridges(
  opts: {
    limit?: number;
    minSimilarity?: number;
    crossTag?: boolean;
  } = {},
): Promise<BridgeCandidate[]> {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.minSimilarity !== undefined)
    params.set("min_similarity", String(opts.minSimilarity));
  if (opts.crossTag) params.set("cross_tag", "true");
  const qs = params.toString();
  return request(`/api/v1/discover/bridges${qs ? `?${qs}` : ""}`);
}

export function listTriangles(
  opts: {
    limit?: number;
    minIntermediates?: number;
  } = {},
): Promise<TriangleCandidate[]> {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.minIntermediates !== undefined)
    params.set("min_intermediates", String(opts.minIntermediates));
  const qs = params.toString();
  return request(`/api/v1/discover/triangles${qs ? `?${qs}` : ""}`);
}

export function classifyBridge(
  nodeAId: string,
  nodeBId: string,
): Promise<BridgeClassification> {
  return request("/api/v1/discover/bridges/classify", {
    method: "POST",
    body: JSON.stringify({ node_a_id: nodeAId, node_b_id: nodeBId }),
  });
}

export function clusterSuggestLinks(body: {
  node_ids?: string[];
  tag_id?: string;
}): Promise<ClusterSuggestResponse> {
  return request("/api/v1/rag/suggest-links/cluster", {
    method: "POST",
    body: JSON.stringify(body),
  });
}

// RAG
export function ragQuery(
  query: string,
  opts: {
    depth?: number;
    mode?: RagMode;
    // ADR-061: optional scope filters. tag_filter is a list of tag IDs with
    // OR semantics; since is an ISO timestamp (e.g. new Date().toISOString()).
    tag_filter?: string[];
    since?: string;
  } = {},
): Promise<RagResponse> {
  return request("/api/v1/rag/query", {
    method: "POST",
    body: JSON.stringify({
      query,
      depth: opts.depth ?? 1,
      mode: opts.mode,
      tag_filter:
        opts.tag_filter && opts.tag_filter.length > 0 ? opts.tag_filter : null,
      since: opts.since ?? null,
    }),
  });
}

export function ragScoped(
  query: string,
  nodeIds: string[],
  customPrompt?: string,
): Promise<RagResponse> {
  return request("/api/v1/rag/scoped", {
    method: "POST",
    body: JSON.stringify({
      query,
      node_ids: nodeIds,
      custom_prompt: customPrompt ?? null,
    }),
  });
}

export function saveAnswer(data: {
  query: string;
  answer: string;
  provenance_ids: string[];
  custom_prompt?: string;
  title?: string;
}): Promise<NodeDetail> {
  return request("/api/v1/rag/save-answer", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

// Admin / embedding jobs
export function getEmbeddingJobs(
  status?: EmbeddingJobStatus,
): Promise<EmbeddingJobList> {
  const qs = status ? `?status=${status}` : "";
  return request(`/api/v1/config/embedding-jobs${qs}`);
}

export function retryEmbeddingJob(jobId: string): Promise<EmbeddingJob> {
  return request(`/api/v1/config/embedding-jobs/${jobId}/retry`, {
    method: "POST",
  });
}

export function retryAllFailedEmbeddingJobs(): Promise<{ retried: number }> {
  return request("/api/v1/config/embedding-jobs/retry-all-failed", {
    method: "POST",
  });
}

export function getAdminStatus(): Promise<AdminStatus> {
  return request("/api/v1/admin/status");
}

export function getStats(): Promise<CorpusStats> {
  return request("/api/v1/admin/stats");
}

export function getActivity(days = 7): Promise<ActivityFeed> {
  return request(`/api/v1/activity?days=${days}`);
}

// ---------------------------------------------------------------------------
// Projects (Phase 9 — ADR-063, ADR-068)
// ---------------------------------------------------------------------------

export function listProjects(): Promise<ProjectSummary[]> {
  return request("/api/v1/projects");
}

export function createProject(data: ProjectCreate): Promise<ProjectDetail> {
  return request("/api/v1/projects", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function getProject(hubId: string): Promise<ProjectDetail> {
  return request(`/api/v1/projects/${hubId}`);
}

export function getProjectScope(hubId: string): Promise<ProjectScope> {
  return request(`/api/v1/projects/${hubId}/scope`);
}

export function patchProjectScope(
  hubId: string,
  patch: ProjectScopeUpdate,
): Promise<ProjectScope> {
  return request(`/api/v1/projects/${hubId}/scope`, {
    method: "PATCH",
    body: JSON.stringify(patch),
  });
}

export function resolveProjectByName(
  name: string,
): Promise<ProjectResolveResponse> {
  const qs = new URLSearchParams({ name }).toString();
  return request(`/api/v1/projects/resolve?${qs}`);
}

// Drafts
export function getDraft(hubId: string): Promise<Draft> {
  return request(`/api/v1/projects/${hubId}/draft`);
}

export function putDraft(hubId: string, content: string): Promise<Draft> {
  return request(`/api/v1/projects/${hubId}/draft`, {
    method: "PUT",
    body: JSON.stringify({ content }),
  });
}

export function deleteDraft(hubId: string): Promise<void> {
  return request(`/api/v1/projects/${hubId}/draft`, { method: "DELETE" });
}

// Sessions
export function startSession(
  hubId: string,
  data: WorkSessionCreate,
): Promise<WorkSession> {
  return request(`/api/v1/projects/${hubId}/sessions`, {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function listSessions(hubId: string): Promise<WorkSession[]> {
  return request(`/api/v1/projects/${hubId}/sessions`);
}

export function patchSession(
  hubId: string,
  sessionId: string,
  patch: WorkSessionUpdate,
): Promise<WorkSession> {
  return request(`/api/v1/projects/${hubId}/sessions/${sessionId}`, {
    method: "PATCH",
    body: JSON.stringify(patch),
  });
}

// Slice 4 — narrative timeline (ADR-064/065/066/072)
export type TimelineResponse = components["schemas"]["TimelineResponse"];
export type TimelineLane = components["schemas"]["TimelineLane"];
export type TimelineEvent = components["schemas"]["TimelineEvent"];
export type StoryEventCreate = components["schemas"]["StoryEventCreate"];
export type TimelinePositionUpdate =
  components["schemas"]["TimelinePositionUpdate"];
export type ActSpan = components["schemas"]["ActSpan"];
export type ActSpanCreate = components["schemas"]["ActSpanCreate"];
export type ProseStatus = NonNullable<TimelineEvent["prose_status"]>;

export function getTimeline(hubId: string): Promise<TimelineResponse> {
  return request(`/api/v1/projects/${hubId}/timeline`);
}

export function createStoryEvent(data: StoryEventCreate): Promise<NodeDetail> {
  return request("/api/v1/nodes/story-event", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function updateTimelinePosition(
  nodeId: string,
  data: TimelinePositionUpdate,
): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${nodeId}/timeline-position`, {
    method: "PATCH",
    body: JSON.stringify(data),
  });
}

// Slice 5: cross-lane drag-and-drop. `remove_from_timeline_node_id`
// null = crossover/copy; set = move.
export type TimelinePlacementRequest =
  components["schemas"]["TimelinePlacementRequest"];

export function placeOnTimeline(
  nodeId: string,
  data: TimelinePlacementRequest,
): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${nodeId}/timeline-placement`, {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function createActSpan(
  hubId: string,
  data: ActSpanCreate,
): Promise<ActSpan> {
  return request(`/api/v1/projects/${hubId}/act-spans`, {
    method: "POST",
    body: JSON.stringify(data),
  });
}

// Slice 5
export type SceneContextResponse =
  components["schemas"]["SceneContextResponse"];
export type SceneContextItem = components["schemas"]["SceneContextItem"];
export type NarrativeDumpRequest =
  components["schemas"]["NarrativeDumpRequest"];
export type NarrativeDumpResponse =
  components["schemas"]["NarrativeDumpResponse"];
export type NarrativeCandidate = components["schemas"]["NarrativeCandidate"];

export function createTimeline(
  hubId: string,
  data: { title: string; content?: string },
): Promise<NodeDetail> {
  return request(`/api/v1/projects/${hubId}/timelines`, {
    method: "POST",
    body: JSON.stringify({ title: data.title, content: data.content ?? "" }),
  });
}

export function getSceneContext(
  hubId: string,
  eventId: string,
  sessionNumber?: number,
): Promise<SceneContextResponse> {
  const qs = sessionNumber ? `?session_number=${sessionNumber}` : "";
  return request(`/api/v1/projects/${hubId}/scene-context/${eventId}${qs}`);
}

export function narrativeDump(
  data: NarrativeDumpRequest,
): Promise<NarrativeDumpResponse> {
  return request("/api/v1/rag/narrative-dump", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

// Entity Arc — evolution-over-time of any node (ADR-081).
export type EntityArc = components["schemas"]["EntityArc"];
export type ArcAppearance = components["schemas"]["ArcAppearance"];

export function getEntityArc(id: string): Promise<EntityArc> {
  return request(`/api/v1/nodes/${id}/arc`);
}

// Reserved narrative tag names — mirror backend constants. Used by the
// character/theme/lore/location list views to identify narrative-role nodes.
export const NARRATIVE_TAGS = {
  CHARACTER: "narrative:character",
  THEME: "narrative:theme",
  LOCATION: "narrative:location",
  // Canon audit (ADR-077): story-specific role types that previously had no
  // first-class representation. Symbols/metaphors recur and accrete meaning;
  // factions are authority/underground structures; open questions are the
  // writer's unresolved threads. All are taggable structure/permanent nodes,
  // linked into scenes via ordinary typed edges — no schema change required.
  SYMBOL: "narrative:symbol",
  FACTION: "narrative:faction",
  OPEN_QUESTION: "narrative:open-question",
  LORE_PREFIX: "narrative:lore-",
  LORE_WORLD_RULE: "narrative:lore-world-rule",
  LORE_HISTORY: "narrative:lore-history",
  LORE_POWER: "narrative:lore-power",
  LORE_FABRIC: "narrative:lore-fabric",
  LORE_BACKSTORY: "narrative:lore-backstory",
  LORE_SECRET: "narrative:lore-secret",
  // Additional lore subtypes surfaced as quick-create categories.
  LORE_ABILITY: "narrative:lore-ability",
  LORE_ARTIFACT: "narrative:lore-artifact",
} as const;

// Slice 2 additions
export type CoverageResponse = components["schemas"]["CoverageResponse"];
export type CoverageTag = components["schemas"]["CoverageTag"];
export type SessionWrapCounts = components["schemas"]["SessionWrapCounts"];
export type LearningMapRequest = components["schemas"]["LearningMapRequest"];
export type LearningMapResponse = components["schemas"]["LearningMapResponse"];
export type LearningMapPhase = components["schemas"]["LearningMapPhase"];
export type LearningMapPhaseSource =
  components["schemas"]["LearningMapPhaseSource"];

export function getCoverage(hubId: string): Promise<CoverageResponse> {
  return request(`/api/v1/projects/${hubId}/coverage`);
}

// Open Threads & Pending Payoffs dashboard (ADR-083).
export type ProjectThreads = components["schemas"]["ProjectThreads"];
export type ThreadItem = components["schemas"]["ThreadItem"];
export type TensionThread = components["schemas"]["TensionThread"];

export function getProjectThreads(hubId: string): Promise<ProjectThreads> {
  return request(`/api/v1/projects/${hubId}/threads`);
}

export function getSessionWrap(
  hubId: string,
  sessionId: string,
): Promise<SessionWrapCounts> {
  return request(`/api/v1/projects/${hubId}/sessions/${sessionId}/wrap`);
}

export function attachNodeToSession(
  hubId: string,
  sessionId: string,
  nodeId: string,
  sessionTagged = true,
): Promise<{ attached: boolean }> {
  return request(
    `/api/v1/projects/${hubId}/sessions/${sessionId}/attach-node`,
    {
      method: "POST",
      body: JSON.stringify({ node_id: nodeId, session_tagged: sessionTagged }),
    },
  );
}

export function generateLearningMap(
  hubId: string,
  body: LearningMapRequest,
): Promise<LearningMapResponse> {
  return request(`/api/v1/projects/${hubId}/learning-map`, {
    method: "POST",
    body: JSON.stringify(body),
  });
}

// Synthesize (project-scoped) — ADR-069 widening
export function ragScopedWithSession(
  query: string,
  nodeIds: string[],
  opts: {
    customPrompt?: string;
    includeSessionFleetings?: boolean;
    sessionId?: string | null;
  } = {},
): Promise<RagResponse> {
  return request("/api/v1/rag/scoped", {
    method: "POST",
    body: JSON.stringify({
      query,
      node_ids: nodeIds,
      custom_prompt: opts.customPrompt ?? null,
      include_session_fleetings: !!opts.includeSessionFleetings,
      session_id: opts.sessionId ?? null,
    }),
  });
}
