import type { components } from "./api-types";

export type NodeDetail = components["schemas"]["NodeDetail"];
export type NodeSummary = components["schemas"]["NodeSummary"];
export type NodeRef = components["schemas"]["NodeRef"];
export type SuggestPermanentResponse = components["schemas"]["SuggestPermanentResponse"];
export type PermanentCandidate = components["schemas"]["PermanentCandidate"];
export type SuggestLinksResponse = components["schemas"]["SuggestLinksResponse"];
export type LinkSuggestion = components["schemas"]["LinkSuggestion"];
export type PaginatedNodes = components["schemas"]["Paginated_NodeSummary_"];
export type TagRef = components["schemas"]["TagRef"];
export type EdgeDetail = components["schemas"]["EdgeDetail"];
export type EdgeType = components["schemas"]["EdgeCreate"]["type"];
export type SourceSummary = components["schemas"]["SourceSummary"];
export type SourceDetail = components["schemas"]["SourceDetail"];
export type SourceCreate = components["schemas"]["SourceCreate"];
// SourceUpdate is generated by openapi-typescript once the backend exposes it.
// Until `pnpm types` runs it may be absent — fall back to a structural type.
export type SourceUpdate = Partial<Omit<SourceCreate, "id">>;
export type SearchResponse = components["schemas"]["SearchResponse"];
export type SearchResult = components["schemas"]["SearchResult"];
export type RagResponse = components["schemas"]["RagResponse"];
export type NodeUsed = components["schemas"]["NodeUsed"];
export type EdgeTraversed = components["schemas"]["EdgeTraversed"];
export type GraphData = components["schemas"]["GraphData"];
export type GraphNodeRef = components["schemas"]["GraphNodeRef"];
export type GraphEdgeRef = components["schemas"]["GraphEdgeRef"];
export type IngestDocumentResponse = components["schemas"]["IngestDocumentResponse"];
export type IngestSourceCreate = components["schemas"]["IngestSourceCreate"];
export type ChunkResult = components["schemas"]["ChunkResult"];
export type LiteratureCandidate = components["schemas"]["LiteratureCandidate"];
export type PendingIngestResponse = components["schemas"]["PendingIngestResponse"];
export type EmbeddingJob = components["schemas"]["EmbeddingJob"];
export type EmbeddingJobCounts = components["schemas"]["EmbeddingJobCounts"];
export type EmbeddingJobList = components["schemas"]["EmbeddingJobList"];
export type EmbeddingJobStatus = EmbeddingJob["status"];
export type AdminStatus = components["schemas"]["AdminStatus"];
// CorpusStats lands in api-types after `pnpm types`. Structural fallback for now.
export type CorpusStats = {
  nodes_by_type: Record<string, number>;
  edges: number;
  sources: number;
  tags: number;
  inbox: number;
  last_processed_at: string | null;
};
// BridgeCandidate is not yet in the generated schema — define manually from backend model
export type BridgeCandidate = { node_a: NodeRef; node_b: NodeRef; similarity: number };

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { "Content-Type": "application/json" },
    cache: "no-store",
    ...options,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`${res.status}: ${text}`);
  }
  if (res.status === 204) return undefined as T;
  return res.json() as Promise<T>;
}

export function createFleetingNode(title: string, content: string): Promise<NodeDetail> {
  return request("/api/v1/nodes/fleeting", {
    method: "POST",
    body: JSON.stringify({ title, content }),
  });
}

export function getInboxNodes(): Promise<NodeSummary[]> {
  return request("/api/v1/nodes/inbox");
}

export function getNode(id: string): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${id}`);
}

export function updateNode(
  id: string,
  patch: {
    title?: string;
    content?: string;
    summary?: string;
    source_id?: string | null;
    tag_ids?: string[] | null;
  },
): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${id}`, {
    method: "PATCH",
    body: JSON.stringify(patch),
  });
}

export function markNodeProcessed(id: string): Promise<NodeDetail> {
  return request(`/api/v1/nodes/${id}/process`, { method: "POST" });
}

export function deleteNode(id: string): Promise<void> {
  return request(`/api/v1/nodes/${id}`, { method: "DELETE" });
}

export function suggestPermanent(id: string): Promise<SuggestPermanentResponse> {
  return request(`/api/v1/rag/suggest-permanent/${id}`, { method: "POST" });
}

export function createPermanentNode(data: {
  title: string;
  content: string;
  summary?: string;
  tag_ids?: string[];
}): Promise<NodeDetail> {
  return request("/api/v1/nodes/permanent", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function listNodes(type?: string, page = 1, pageSize = 50): Promise<PaginatedNodes> {
  const params = new URLSearchParams({ page: String(page), page_size: String(pageSize) });
  if (type) params.set("type", type);
  return request(`/api/v1/nodes?${params}`);
}

export function createLiteratureNode(data: {
  title: string;
  content: string;
  summary?: string;
  source_id: string;
  tag_ids?: string[];
}): Promise<NodeDetail> {
  return request("/api/v1/nodes/literature", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function createStructureNode(data: {
  title: string;
  content: string;
  summary?: string;
}): Promise<NodeDetail> {
  return request("/api/v1/nodes/structure", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function searchNodes(q: string, limit = 10): Promise<NodeRef[]> {
  const params = new URLSearchParams({ q, limit: String(limit) });
  return request(`/api/v1/nodes/search?${params}`);
}

// Tags
export function listTags(): Promise<TagRef[]> {
  return request("/api/v1/tags");
}

export function createTag(name: string, color?: string): Promise<TagRef> {
  return request("/api/v1/tags", {
    method: "POST",
    body: JSON.stringify({ name, color }),
  });
}

// Edges
export function createEdge(data: {
  from_id: string;
  to_id: string;
  type: EdgeType;
  note?: string;
}): Promise<EdgeDetail> {
  return request("/api/v1/edges", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function deleteEdge(edgeId: string): Promise<void> {
  return request(`/api/v1/edges/${edgeId}`, { method: "DELETE" });
}

// RAG
export function suggestLinks(nodeId: string): Promise<SuggestLinksResponse> {
  return request(`/api/v1/rag/suggest-links/${nodeId}`, { method: "POST" });
}

// Sources
export function listSources(): Promise<SourceSummary[]> {
  return request("/api/v1/sources");
}

export function getSource(id: string): Promise<SourceDetail> {
  return request(`/api/v1/sources/${id}`);
}

export function createSource(data: Omit<SourceCreate, "id">): Promise<SourceDetail> {
  return request("/api/v1/sources", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

export function updateSource(id: string, data: SourceUpdate): Promise<SourceDetail> {
  return request(`/api/v1/sources/${id}`, {
    method: "PATCH",
    body: JSON.stringify(data),
  });
}

export function deleteSource(id: string): Promise<void> {
  return request(`/api/v1/sources/${id}`, { method: "DELETE" });
}

export function openSource(id: string): Promise<{ opened: string; warning?: string }> {
  return request(`/api/v1/sources/${id}/open`);
}

// Search
export function searchSemantic(query: string, limit = 20): Promise<SearchResponse> {
  return request("/api/v1/search/semantic", {
    method: "POST",
    body: JSON.stringify({ query, limit }),
  });
}

export function searchFulltext(query: string, limit = 20): Promise<SearchResponse> {
  return request("/api/v1/search/fulltext", {
    method: "POST",
    body: JSON.stringify({ query, limit }),
  });
}

export function searchHybrid(query: string, limit = 20): Promise<SearchResponse> {
  return request("/api/v1/search/hybrid", {
    method: "POST",
    body: JSON.stringify({ query, limit }),
  });
}

// Graph
export function getGraphData(includeFlecting = true): Promise<GraphData> {
  return request(`/api/v1/graph/data?include_fleeting=${includeFlecting}`);
}

// Ingest
export function ingestDocument(body: {
  content: string;
  source_id?: string;
  source?: IngestSourceCreate;
}): Promise<IngestDocumentResponse> {
  return request("/api/v1/ingest/document", {
    method: "POST",
    body: JSON.stringify(body),
  });
}

export function getPendingIngest(sourceId: string): Promise<PendingIngestResponse> {
  return request(`/api/v1/ingest/pending/${sourceId}`);
}

export function clearPendingIngest(sourceId: string): Promise<void> {
  return request(`/api/v1/ingest/pending/${sourceId}`, { method: "DELETE" });
}

// Discover
export function listOrphans(opts: {
  limit?: number;
  offset?: number;
  nodeType?: string;
} = {}): Promise<NodeSummary[]> {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.offset !== undefined) params.set("offset", String(opts.offset));
  if (opts.nodeType) params.set("node_type", opts.nodeType);
  const qs = params.toString();
  return request(`/api/v1/discover/orphans${qs ? `?${qs}` : ""}`);
}

export function listStale(opts: {
  limit?: number;
  offset?: number;
  nodeType?: string;
  excludeFleeting?: boolean;
} = {}): Promise<NodeSummary[]> {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.offset !== undefined) params.set("offset", String(opts.offset));
  if (opts.nodeType) params.set("node_type", opts.nodeType);
  if (opts.excludeFleeting !== undefined)
    params.set("exclude_fleeting", String(opts.excludeFleeting));
  const qs = params.toString();
  return request(`/api/v1/discover/stale${qs ? `?${qs}` : ""}`);
}

export function listBridges(opts: {
  limit?: number;
  minSimilarity?: number;
} = {}): Promise<BridgeCandidate[]> {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.minSimilarity !== undefined)
    params.set("min_similarity", String(opts.minSimilarity));
  const qs = params.toString();
  return request(`/api/v1/discover/bridges${qs ? `?${qs}` : ""}`);
}

// RAG
export function ragQuery(query: string, depth = 1): Promise<RagResponse> {
  return request("/api/v1/rag/query", {
    method: "POST",
    body: JSON.stringify({ query, depth }),
  });
}

export function ragScoped(
  query: string,
  nodeIds: string[],
  customPrompt?: string,
): Promise<RagResponse> {
  return request("/api/v1/rag/scoped", {
    method: "POST",
    body: JSON.stringify({
      query,
      node_ids: nodeIds,
      custom_prompt: customPrompt ?? null,
    }),
  });
}

export function saveAnswer(data: {
  query: string;
  answer: string;
  provenance_ids: string[];
  custom_prompt?: string;
  title?: string;
}): Promise<NodeDetail> {
  return request("/api/v1/rag/save-answer", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

// Admin / embedding jobs
export function getEmbeddingJobs(status?: EmbeddingJobStatus): Promise<EmbeddingJobList> {
  const qs = status ? `?status=${status}` : "";
  return request(`/api/v1/config/embedding-jobs${qs}`);
}

export function retryEmbeddingJob(jobId: string): Promise<EmbeddingJob> {
  return request(`/api/v1/config/embedding-jobs/${jobId}/retry`, { method: "POST" });
}

export function retryAllFailedEmbeddingJobs(): Promise<{ retried: number }> {
  return request("/api/v1/config/embedding-jobs/retry-all-failed", { method: "POST" });
}

export function getAdminStatus(): Promise<AdminStatus> {
  return request("/api/v1/admin/status");
}

export function getStats(): Promise<CorpusStats> {
  return request("/api/v1/admin/stats");
}
